steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA"
      - "-f"
      - "Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "telegram-bot"
      - "--image"
      - "gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "APP_VERSION=$COMMIT_SHA,BOT_USERNAME=Suporte_ir_bot"
      - "--set-secrets"
      - "TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest"

images:
  - "gcr.io/$PROJECT_ID/telegram-bot:$COMMIT_SHA"
